<?php

namespace Sun\Suntest;

use Illuminate\Support\ServiceProvider;

class SuntestServiceProvider extends ServiceProvider
{
    //延迟加载
    protected $defer    =   true;
    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
        $this->loadViewsFrom(__DIR__.'/views','Suntest');
        $this->publishes([
            __DIR__.'/views' => base_path('resources/views/vendor/suntest'),  // 发布视图目录到resources 下
            __DIR__.'/config/suntest.php' => config_path('suntest.php'), // 发布配置文件到 laravel 的config 下
        ]);
    }

    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
        $this->app->singleton('suntest',function($app){
            return  new Suntest($app['session'],$app['config']);
        });
    }

    public function provides()
    {
//        return parent::provides(); // TODO: Change the autogenerated stub
        return ['suntest'];
    }
}
